### ISSUE TITLE
Only vote on third reading bills

### ISSUE THREAD

**Issue by KipCrossing** [voteflux/voting_app#10]
Because there are so many bills to be voted on, we need to find a way to cut down on the available bills on the list. one simple solution (that doesn't require searching or filters) is to limit voting to only bills that have the third reading available. The other bills can be still viewed, just sorted lower down in the list, with the tag: *Upcoming Bills*. Therefore the **status widget** will have to be modified to include this tag. I recommend that the bills be ordered like:

- open
- upcoming
- closed

The *voted* tag may be mixed within these 3 or sorted into its own section - the voted bills should be also accessible within the Profile page under *History*.

**Comment by KipCrossing** [comment]
Also, will need - "Voting not open" on the voting widget, w/ "Notify me" switch

**Comment by BenBallingall** [comment]
I wish there was a way that was easier to make, but it has to be search and filter options.

segmented list idea leaves the newest and hottest bills that are being promoted and tabled by current parties at the far bottom of the list - and more than likely floods the top of the list that everyone will first see with the drier, sure thing bureacratic bills.

people are going to be coming to the app, if they're politically aware, searching for bills they already know and that have the backing of established parties/groups - there are a few instances when bills are most interesting to people near the end of the parliamentary cycle, e.g the government snuck a sneaky bill though the Lower House and now the Senate needs to be told that nobody wants them to pass it or, a minority parties bill somehow made it past the house it was proposed in and we want to make sure it isn't altered or struck down in it's second house. 
but really.. we can't say when a bill is most interesting to people, or more importantly, most likely to garner virality and push people to vote on it in the app.
when it's first introduced? when it has passed first house and first gets introduced to the second house, or when it's already been debated by all parliamentarians and it's up to it's final reading in vote (generally a foregone conclusion at this point).

it's got to be searchable - key words, bill title, proposing MP name, proposing parties

there should be filters that you can use to refine the list that you see as 163 bills is overwhelming, it would be very rare that someone would ever search with every filter on.
the filters should be something like - House, Area of Government/Portfolio, proposing party, current reading, bill type

**Comment by oscarmanderj** [comment]
I agree. 

It has to be search and filter options. 

This will not be too difficult. We can use elastic search for this to make everything snappy.

**Comment by XertroV** [comment]
I guess we don't really care about getting a result before parliament does in all cases right? Was going to ask if there were any times where the third reading and voting (in parliament) occurred v close together, but I don't think that's an issue in this case.

Seems like a sensible solution

**Comment by KipCrossing** [comment]
Yes, changing vote would be a important if you voted on the first reading and the bill had a third Reading. "A bill that you have voted on has updated it's details, click here to review".

**Comment by ptboyer** [comment]
> use elastic search

I think it's also important to recognise that we should minimise complexity (without elastic search) everywhere we can. It'll be fast enough for the number of users initially on the app. It's an alpha, not gold just yet. ;)

> w/ "Notify me" switch

Scope it to a later release. I feel that notifications are non-essential for alpha, the main user experience should be focused on:

Register -> Login -> View Bills -> View Bill -> (voting available) Vote or (voting not open).

> changing vote would be a important if you voted on the first reading

We can have a user query all the bills they've voted for (by looking at revisions/votables (below)) and then SELECT bills WHERE the bill's latest revision has no vote from this user.

Because new revisions occur when there are changes, but each reading does not necessarily introduce new revisions.

- Bill (current reading = 3)
- nothing changed on the third reading
- Revision/Votable (reading = 1)
- Revision/Votable (reading = 0)

For the alpha perhaps it would be best to treat every bill revision as a separate entity to vote for?

Bill 1-to-M Revision (Votable) (1,2,3,4 ...) M-to-M Vote (user_id, votable_id)

**Comment by XertroV** [comment]
> We can use elastic search for this to make everything snappy.

Min price I saw just now was $16 USD/mo. It sucks that we're in a position where that's untennably high, but in essence, whatever we implement needs to have $0 ongoing costs.
