### ISSUE TITLE
Onboarding & Tutorial "slides"

### ISSUE THREAD

**Issue by BenBallingall** [voteflux/voting_app#130]
Suggestions for current state (really a tiny bit in the future) DigiPol onboarding and tutorial slides.

Document can be found and edited at https://docs.google.com/document/d/1uvm1OB3Slj6wcVt5XwZmkyavBeaVDLOWD2-iRgMtp6E/edit 

@oscarmanderj @KipCrossing  plain text below, i may have butchered the markdown :P 

---

### 1. Welcome to DigiPol!

The voting app where you can have your say!
DigiPol brings you every bill in Federal Parliament and a selection of hot national issues.

We know that’s a lot, so we’ve made it easier to find the bills and issues that are important to you. Select some of the topics that interest you:

*List of topics*:
- Citizens
- Nature
- National Development
- Borders
- Economy
- Communications

You'll be able to search keywords and change these selections later, but for now you’ll have some **bill** and **issue** **cards** at the top of your feed. 

_Let's see what information you’ll get with them_ or _skip to get started (you can revisit this later in Settings_ ->

### 2. Cards
You’ll be provided with some important information to help you find what you’re looking for.

The Bill title and it’s portfolio or sponsor
- *highlight explaining portfolios/sponsors*

 You can get a quick idea of how the bill is progressing through parliament using the below key:
- *highlight explaining the house iron widget* (explains starting house, current progression)

The current vote results
- *highlight explaining Pie Graph* (explains current vote Y/N) 

Date lodged
- *highlight date*

The bills status in **DigiPol**
- *highlight bill status - explain DigiPol statuses*

Once you’ve found a bill that interests you, you’ll be taken to the relevant Bill Page.
It’s nearly time to vote!

_Find out more about Bill Pages_ or _skip_->

### 3. Bill Pages

The **Bill Page** displays all of the previous information in more detail, and allows you to access the documents tabled in your Federal Parliament.
*highlight Explanatory Memorandum - explain*
*highlight Bill Reading - explain*

From there, voting is easy! Simply scroll down to find where to make your vote. 
Practice making a vote by tapping yes or below.
*Dummy vote widget*

You’ll see confirmation of your vote and your unique vote receipt number. 

_Find out how we securely record your vote_ or _skip_ ->

### 4. Your Details
We believe that voter privacy and vote security are important. Instead of using your personal details, **DigiPol** generates you a unique **VoterKey** that is used to record your vote on the secure blockchain. 
*Tap to see your unique key*
*Tap - you can match this with your vote receipt number to verify your votes on the blockchain*

By keeping your personal details and your **VoterKey** separated, **DigiPol** lets you decide how involved you get with your democracy. After you’ve had your vote, there’s more you can do!

_Find out how else you can interact_ or _skip_ ->

### 5. The DigiPol Community

We want to use this technology to change how you interact with your Federal Parliament, and each other. Here are a couple of extra things you can do within **DigiPol**.

**Share** bills and vote results - gather awareness or let everyone know how you voted
*sharing example*
Participate in the **comments section** below each bill - summarise what it’s about, in your own words.
*explanation of commenting (private key generates ID for commenting)

You’re all set up and ready to use DigiPol! Together we can make a difference. 

_Enter app_ ->

**Comment by KipCrossing** [comment]
Suggestions for current state (really a tiny bit in the future) DigiPol onboarding and tutorial slides.

Document can be found and edited at https://docs.google.com/document/d/1uvm1OB3Slj6wcVt5XwZmkyavBeaVDLOWD2-iRgMtp6E/edit 

@oscarmanderj @KipCrossing  plain text below, i may have butchered the markdown :P 

---

### 1. Welcome to DigiPol!

The voting app where you can have your say!
DigiPol brings you every bill in Federal Parliament and a selection of hot national issues.

We know that’s a lot, so we’ve made it easier to find the bills and issues that are important to you. Select some of the topics that interest you:

*List of topics*:
- Citizens
- Nature
- National Development
- Borders
- Economy
- Communications

You'll be able to search keywords and change these selections later, but for now you’ll have some **bill** and **issue** **cards** at the top of your feed. 

_Let's see what information you’ll get with them_ or _skip to get started (you can revisit this later in Settings_ ->


### 2. Cards
You’ll be provided with some important information to help you find what you’re looking for.

The Bill title and it’s portfolio or sponsor
- *highlight explaining portfolios/sponsors*

 You can get a quick idea of how the bill is progressing through parliament using the below key:
- *highlight explaining the house iron widget* (explains starting house, current progression)

The current vote results
- *highlight explaining Pie Graph* (explains current vote Y/N) 

Date lodged
- *highlight date*

The bills status in **DigiPol**
- *highlight bill status - explain DigiPol statuses*

Once you’ve found a bill that interests you, you’ll be taken to the relevant Bill Page.
It’s nearly time to vote!

_Find out more about Bill Pages_ or _skip_->

### 3. Bill Pages

The **Bill Page** displays all of the previous information in more detail, and allows you to access the documents tabled in your Federal Parliament.
*highlight Explanatory Memorandum - explain*
*highlight Bill Reading - explain*


From there, voting is easy! Simply scroll down to find where to make your vote. 
Practice making a vote by tapping yes or below.
*Dummy vote widget*

You’ll see confirmation of your vote and your unique vote receipt number. 

_Find out how we securely record your vote_ or _skip_ ->


### 4. Your Details
We believe that voter privacy and vote security are important. Instead of using your personal details, **DigiPol** generates you a unique **VoterKey** that is used to record your vote on the secure blockchain. 
*Tap to see your unique key*
*Tap - you can match this with your vote receipt number to verify your votes on the blockchain*

By keeping your personal details and your **VoterKey** separated, **DigiPol** lets you decide how involved you get with your democracy. After you’ve had your vote, there’s more you can do!

_Find out how else you can interact_ or _skip_ ->


### 5. The DigiPol Community

We want to use this technology to change how you interact with your Federal Parliament, and each other. Here are a couple of extra things you can do within **DigiPol**.

**Share** bills and vote results - gather awareness or let everyone know how you voted
*sharing example*
Participate in the **comments section** below each bill - summarise what it’s about, in your own words.
*explanation of commenting (private key generates ID for commenting)

You’re all set up and ready to use DigiPol! Together we can make a difference. 

_Enter app_ ->

**Comment by oscarmanderj** [comment]
I'm starting to think that this amount of information needs to be in a 'help' section/or other rather than on the on-boarding slides.

I think we are overloading them before they even see the process. 

The initial slides in my opinion should be an overview of the app. So just 5 brief slides about it. Not going into each specific UI component.

Then once they are in the app, we could have "help" toggle function. If it is ON, then more help data is displayed.

**Comment by KipCrossing** [comment]
That's a good point. It's so hard not to overthink these slides.

**Comment by BenBallingall** [comment]
Definitely.
Voice chat it out?

**Comment by BenBallingall** [comment]
![DigiPol Video Onboard (rough)](https://user-images.githubusercontent.com/48424114/91536049-7ace7a00-e957-11ea-8f78-673b05969115.gif)

**Comment by BenBallingall** [comment]
mic drop

**Comment by KipCrossing** [comment]
using a different solution
