### ISSUE TITLE
Restrict voting to only open bills

### ISSUE THREAD

**Issue by oscarmanderj** [voteflux/voting_app#63]
To do: Replace buttons with "Voting has closed" once the bill can no longer be voted on

**Comment by KipCrossing** [comment]
We should also remove any bills that didn't end in the current year (eg: 2020)
 - could be API side: discuss

**Comment by oscarmanderj** [comment]
Yes, both functions should be done api side

**Comment by oscarmanderj** [comment]
Yes the value of both should be in the object returned from the all bills endpoint

**Comment by okdaithi** [comment]
There a deeper UX question to resolve here:

**_Should users have the ability to vote on a bill after it has received assent i.e. closed?_**

An elected representative can't vote on a bill that has received assent so the UX could define that a Digipol user can't vote on it either.

However, I propose that the UX should allow users to maintain the ability to vote on a bill after assent.

Simply put, bills are passed. Some are good, some are bad. 

At the core of our philosophy is error correction. Error correction starts with error detection.

One of the errors we want to detect are the bills that may no longer have the support of the citizens due to them being, or becoming bad.

People should be encouraged to change their mind and position on legislation based on receiving updated information. 

This is our error correction process.

I believe that Digipol would be serving the users by providing that outlet - the ability to vote against, or for, bills that may have come and gone, but are not yet forgotten.

It's not a crucial part of the UX which needs to be addressed with any priority. I think we should design the experience to let users know that they _can_ vote on the bill, even though the bill has already passed. I believe that user experience will help us to explain our philosophy and mission.

In order to prevent bill clutter, the feature to vote on past bills should probably be implemented as an opt-in for users to select in settings menu.

**Comment by RedBaron2104** [comment]
I appreciate Daithi's comment and intent but wonder about the UX.

What you've said is an intention that has to be understood by the user or it may end up being extraneous information. How is this quite specific intention communicated and a habit built around it? I wonder if this might be quite a large piece of behaviour mod.

Without that being explicitly understood by the user, you run the risk of them feeling, "why is this bill I can't affect cluttering up my interface?" It might come off as sloppy information management and deprioritise the core activity of engaging with an active bill.

I think it's valid that this does speak to a larger culture change piece, but perhaps we should reflect on scope and capacity within a finite system in that regard.

There is a kind of balance with: what amount of effort can we reasonably expect a user to undertake with the accessibility we can deliver? And, what is the background culture of effort in this domain?

**Comment by KipCrossing** [comment]
@oscarmanderj create an "only open" filter and haveit on by default.

Also, change "Filter by date" to "Sort by date"

**Comment by KipCrossing** [comment]
Fixed in #129 

Open a new issue if you want to have a discussion about more rules around voting time-frames.
