### ISSUE TITLE
Categorising Bills 

### ISSUE THREAD

**Issue by oscarmanderj** [voteflux/voting_app#90]
With so many bills it's hard to navigate. 

I think we should implement some kind of Tagging system.

For example, we have the tags "Environment" "Banking" "Military" etc, and each bill gets tagged as it's added into the db. The user can then filter by tag to easily find subjects.

**Comment by KipCrossing** [comment]
Good idea. Have no idea how to automate it. Shotty not being the one who manually categorises each one.

**Comment by BenBallingall** [comment]
if you check bill pages on aph.gov.au - bills are categorised by portfolio 
Agriculture, Water and the Environment
Attorney-General's
Defence
Education, Skills and Employment
Finance
Foreign Affairs and Trade
Health
Home Affairs
Industry, Science, Energy and Resources
Infrastructure, Transport, Regional Development and Communications
Parliamentary Departments
Prime Minister and Cabinet
Social Services
Treasury
Veterans' Affairs (part of the Defence Portfolio) 

see https://www.directory.gov.au/portfolios

but i think best start for filter options officially.
Proposing party could work eventually, but will probably need more thorough API as aph.gov.au doesn't mention generally - bu would work for onboarding other parties members
also could do "bill type" - but this is generally just gonna be "government" or "private members" afaik

**Comment by BenBallingall** [comment]
https://github.com/voteflux/voting_app/issues/10#issuecomment-601513412

**Comment by XertroV** [comment]
re: catagorization - had a think about this 2015/6 particularly re: user generated bills: short version is I think general categorization is impossible.

However in our case I think @BenBallingall is on the money. I was going to suggest doing it by the ministry the bill comes out of (well, the associated MP's rather than the ministry itself, which is executive branch). If APH do that (presumably "portfolio" is a little bit looser) then we should just use that. It's simple, and means that if people go looking for stuff (either from APH to our app, or vice versa) things will be easier to find.

**Comment by XertroV** [comment]
The other thing is getting filtering for future/open/closed bills, that will help a bunch too.

**Comment by KipCrossing** [comment]
> The other thing is getting filtering for future/open/closed bills, that will help a bunch too.

That's easy

> If APH do that (presumably "portfolio" is a little bit looser) then we should just use that

Show a link with a table or any way to connect a bill with a "portfolio" (or some such) and we have a plan. Otherwise this discussion will get lost in the *'nice to have'* ether.

**Comment by XertroV** [comment]
> Show a link with a table or any way to connect a bill with a "portfolio" (or some such) and we have a plan. Otherwise this discussion will get lost in the 'nice to have' ether.

As in we don't have a way atm to link the two? Hmm, yeah that's probs blocker number.1. Going to have a quick squiz now.

**Comment by XertroV** [comment]
Definitely _looks_ like it should be possible:

![image](https://user-images.githubusercontent.com/1046448/82137012-1c253a80-9857-11ea-8852-42d2e7dcd039.png)

**Comment by XertroV** [comment]
Another dimension we should allow filter/search by is something like the MP who sponsored the bill.

**Comment by KipCrossing** [comment]
Great spotting! 

@XertroV I'll make you a deal. Give me some blockchain action and I'll get this happening ;)

**Comment by XertroV** [comment]
On this note, I am not sure if bills introduced by opposition will have a portfolio, but private member bills won't have a portfolio, so just "private member bills" is probs good for these kind

![image](https://user-images.githubusercontent.com/1046448/82137083-1ed45f80-9858-11ea-9359-611c6dfc6c91.png)

**Comment by XertroV** [comment]
Deal

**Comment by KipCrossing** [comment]
From [aph.gov.au](https://www.aph.gov.au/About_Parliament/House_of_Representatives/Powers_practice_and_procedure/00_-_Infosheets/Infosheet_7_-_Making_laws):


*Under Australia’s Constitution the federal Parliament can make laws only on certain matters. These include: international and interstate trade; foreign affairs; defence; immigration; taxation; banking; insurance; marriage and divorce; currency and weights and measures; post and telecommunications; and invalid and old age pensions.*

---

These could be a pretty legit categorizing system. All we would need to do is get a list of terms for each one and use our existing search filter to obtain instances of the terms.

For example:
**Defence** would have the following terms:
- Army
- Navy
- Airforce
- War
- Defence
- Military

And so on...

**Comment by XertroV** [comment]
@KipCrossing - how would you categorize legislation relating to the Adani mine?

- International trade is involved
- National trade is involved (because competition, etc)
- Infrastructure is involved
- Local economy is involved
- Tourism is involved
- Environment is involved

And consider the case of multiple interdependent bills. Presuming we did have some categorization for the "parent" legislation, if minor dependent legislation was introduced that _didn't_ fit neatly into the categorization for the "parent" legislation, how would you categorize it?

Note: these questions are rhetorical and being used as a device to attempt to demonstrate the insufficiency of naive categorization. If we can deal with these questions concretely I think we've made progress.

**Comment by XertroV** [comment]
Note: we _could_ do "soft" categories, like _if bill *B1* affects *anything* in category C1, from a reasonable person's point of view, then B1 is in C1_.

However, if we do that it is **_unsafe_** to do delegation based on category. I mention this (and ask the above questions) particularly because _delegation based on category_ is a really popular idea, but every idea I've heard or created around implementation has resulted in some contradiction somewhere.

**_I thus believe delegation by category to be impossible._** (until an implementation is found, if ever)

**Comment by XertroV** [comment]
If we went this way, I strongly advise against calling them "categories", rather "tag" is much more intuitive and is _less concrete_ a relationship, so ppl likely will see why 'delegation by tag' isn't easy/possible. It also opens us up to adding more tags ad-hoc in future.

**Comment by oscarmanderj** [comment]
Calling these tags is fine for this. Same UX really

In response to categories:

Could bills have multiple categories? 

Does delegation by category have to be so concrete? By this I mean - If I delegate my vote for category X to one person and category Y to another, and a Bill comes up that is X & Y could my vote be split?

**Comment by BenBallingall** [comment]
doesn't community suggested hashtag fix a lot of this?

i'd just be able to create the #benballingallvotes hashtag, you can search it and see all the votes i'd be having a say on if you delegate to me according to that hashtag. You'd maybe need a way to prioritise your delegates for times where they'd vote on the same bill, only where there is a clash. 
and you'd probably need a mechanism to be able to signal how you'd vote as a delegate.

but this is also crazy out of scope atm - delegation etc. 

so, so for voting_app, we're not reinventing the wheel and parliament yet, we use their categories. portfolios.

**Comment by okdaithi** [comment]
As people have outlined above, the taxonomy of bills can be a tricky process.

IMO, it's best to work with any existing standards which exist outside of us (in this case, the various descriptors used by aph.gov.au). I would initially categorise bills simply either Govt portfolio or the party who proposed it.

Looking at APH.gov.au, each bill has the following descriptors & default attributes

Type: [Government, Private]
(If Type = Government -> Portfolio, else if Type = Private -> Sponsor)

Portfolio: [list of all Govt depts]
Sponsor: [list of non-Govt members]

Party can be derived from Sponsor. In some instances, string passed includes Party abbreviation.

Originating House: [HoR, Senate
Status: [Not Proceeding, Before Reps, Before Senate, Assent, etc]

**Comment by RedBaron2104** [comment]
In principle, I agree with Daithi that if there is a formal convention then it should be followed because this is an official process.

I don't think this precludes the inclusion of what we might call 'more punter friendly' systems of categorisation. We should be able to test different taxonomies with basic prototypes to check for preference. Something like a tag or interest overlay might help people who are unfamiliar with political terminology be best directed to the things they're interested in or passionate about.

**Comment by RedBaron2104** [comment]
A neat gamefied user experience might be to include a political quiz as part of the induction or upon arriving in the 'Bill Hub' (what I'm using as an interim name for the higher level space from which the various bill paths emanate). This quiz could be like a political compass type thing or to discern areas of focus interest and could work in tandem with our taxonomies and categorisation schemes.

**Comment by KipCrossing** [comment]
@RedBaron2104 what type of question were you thinking would go in the quiz?

**Comment by BenBallingall** [comment]
We always have a bit of a curve ball here coz "DigiPol" doesn't wanna reinvent anything in politics - DigiPol is more like "this is the system, we put it online for everyone". So I'm a little hesitant for DigiPol to be like telling people what they think is important via anything other than "official" government definitions.

IN SAYING THAT - "someone" (not DigiPol) could release a "widget" that people could select to enable in settings/profile that allows them to do all this. Y'know what I mean? Like a browser add-on from a "different group". This group/widget could allow people to crowdsource categories or whatever.

Hope that's making sense.

**Comment by nathanturk2** [comment]
Hey KipCrossing

**Comment by KipCrossing** [comment]
https://1j56c60pb0.execute-api.ap-southeast-2.amazonaws.com/dev/bill

Then endpoint to play with the data

**Comment by KipCrossing** [comment]
@nathanturk2

use with https://requests.readthedocs.io/en/master/

**Comment by KipCrossing** [comment]
A suggestion to simplify the topics:
- Citizens
- Nature
- National Development
- Borders
- Economy
- Communications
- Aged Care


These arise from bundling the domains that are with the portfolios and the domains that are outlined by the constitution. My working may be found here: https://docs.google.com/document/d/1g9GTSfyYcz_N41zezVdYW1AOxYf7MdIZKcPYU2pqOkg/edit?usp=sharing

**Comment by KipCrossing** [comment]
https://1j56c60pb0.execute-api.ap-southeast-2.amazonaws.com/dev/bill

Got the list of topics at the endpoint @oscarmanderj

**Comment by KipCrossing** [comment]
How to sort bills:

Sort based on total weighting (W)

Where:
W = w1 + w2 + w3 + w4

w1 = number of tags the user and bill have in common

w2 = number of users key word is in the bill 

w3 = (365 - (today- start date))/365 OR 0 (if < 0)

w4 = (vote count)/(Largest bill vote count)

**Comment by KipCrossing** [comment]
@oscarmanderj TODO
- [x] tag bill cards
- [ ] topics work in search
- [ ] replace the text with icons/chips in bill cards
- [ ] make default filter based on above (can leave out W2)
