### ISSUE TITLE
The App name

### ISSUE THREAD

**Issue by oscarmanderj** [voteflux/voting_app#95]
DigiPol is not strong enough - I think we will get the best result if we crowdsource it through the discord.

Does someone want to lead this?

**Comment by KipCrossing** [comment]
We should crowdsource this. Get a name + logo. The winner gets a reward.

I'll pitch in $50

**Comment by KipCrossing** [comment]
AusVote

**Comment by KipCrossing** [comment]
@RedBaron2104

Did you and Lauren want to have a think about this?

**Comment by KipCrossing** [comment]
'PowerVote' or 'VotePower'

**Comment by KipCrossing** [comment]
"Votey McVote"

**Comment by connorhsm** [comment]
RedBaron's [doc](https://docs.google.com/document/d/1kTWrFO2zHWddXddI1RpGXq4d8aybtblEhIxsTYP7Fic/edit)

**Comment by connorhsm** [comment]
The general consensus from this weeks meeting was this has been open for long enough and no other real contender has really come from it.

I am of the opinion DigiPol is all we need. As far as I know, it was something that come to mind quickly and easily. It has since been portrayed as temporary name, but really has no glaring issue and seems to have settled well to be a lot more than just a temp name.

In the presence of Ben, Kip, Baron and myself we decided it would be best to wrap this up and keep a request for any further suggestions to only be announced within the Discord with this weekend as the deadline.

I say that we close this issue by 9:30PM Eastern at the next Monday meeting (17th August)

**Comment by KipCrossing** [comment]
Closing as no other name is better than DIGIPOL!!!!
